# Generated by Django 4.0.2 on 2022-04-10 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('case', models.TextField(max_length=1000)),
                ('Choice_amount', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='ApproveProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollsAPI.proposal')),
            ],
        ),
    ]
