# Generated by Django 4.0.2 on 2022-04-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='option1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='proposal',
            name='option2',
            field=models.CharField(default='', max_length=500),
        ),
    ]
